const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYES_ERROR: 2,
    DATABASE_ERROR: 3,
    INVALID_CREDENTIALS: 4
};
export default EErrors;
/*
  // General errors
  SERVER_ERROR: 'SERVER_ERROR',

  // Product errors
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',

  // User errors
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
  USER_NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Cart errors
  CART_EMPTY: 'CART_EMPTY',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_OUT_OF_STOCK: 'CART_ITEM_OUT_OF_STOCK',


  // Admin errors
  ADMIN_ONLY: 'ADMIN_ONLY',
  PRODUCT_CREATION_FAILED: 'PRODUCT_CREATION_FAILED',

  */